import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

interface Star {
  name: string
  races: string[]
  price: number | null
  ma: number; st: number; ag: number; av: number
  skills: string[]
  notes: string | null
  includedWith: string | null
}

const STARS: Star[] = [
  { name: 'Anqi Panqi',                              races: ['Lizardman'],                                                                                                                                         price: 210000, ma: 7, st: 4, ag: 1, av: 9,  skills: ['Loner', 'Block', 'Grab', 'Stand Firm'],                                                                                                                                  notes: null,                          includedWith: null },
  { name: 'Asperon Thorn',                           races: ['Dark Elf', 'Elf', 'High Elf'],                                                                                                                        price: 160000, ma: 6, st: 3, ag: 4, av: 8,  skills: ['Hail Mary Pass', 'Kick-off Return', 'Loner', 'Pass', 'Safe Throw', 'Sure Hands'],                                                                              notes: null,                          includedWith: null },
  { name: 'Barik Farblast',                          races: ['Dwarf'],                                                                                                                                              price:  60000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Hail Mary Pass', 'Pass', 'Secret Weapon', 'Strong Arm', 'Sure Hands', 'Thick Skull'],                                                               notes: null,                          includedWith: null },
  { name: 'Bertha Bigfist',                          races: ['Amazon'],                                                                                                                                             price: 290000, ma: 6, st: 5, ag: 2, av: 9,  skills: ['Loner', 'Bone-head', 'Break Tackle', 'Dodge', 'Mighty Blow', 'Thick Skull', 'Throw Team-Mate'],                                                             notes: null,                          includedWith: null },
  { name: 'Big Jobo Hairyfoot',                      races: ['Halfling', 'Ogre'],                                                                                                                                   price: 120000, ma: 4, st: 3, ag: 2, av: 8,  skills: ['Loner', 'Dirty Player', 'Tackle', 'Wrestle', 'Stand Firm', 'Stunty'],                                                                                     notes: null,                          includedWith: null },
  { name: 'Bilerot Vomitflesh',                      races: ['Chaos', 'Nurgle'],                                                                                                                                    price: 180000, ma: 4, st: 5, ag: 2, av: 9,  skills: ['Dirty Player', 'Disturbing Presence', 'Foul Appearance', 'Loner'],                                                                                          notes: null,                          includedWith: null },
  { name: 'Bomber Dribblesnot',                      races: ['Chaos Pact', 'Goblin', 'Ogre', 'Orc', 'Underworld'],                                                                                                  price:  60000, ma: 6, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Accurate', 'Bombardier', 'Dodge', 'Right Stuff', 'Secret Weapon', 'Stunty'],                                                                       notes: null,                          includedWith: null },
  { name: 'Bo Gallanté',                             races: ['High Elf'],                                                                                                                                           price: 160000, ma: 8, st: 3, ag: 4, av: 7,  skills: ['Dodge', 'Loner', 'Side Step', 'Sprint', 'Sure Feet'],                                                                                                    notes: null,                          includedWith: null },
  { name: 'Boomer Eziasson',                         races: ['Dwarf', 'Norse'],                                                                                                                                     price:  60000, ma: 4, st: 3, ag: 2, av: 9,  skills: ['Loner', 'Accurate', 'Block', 'Bombardier', 'Secret Weapon', 'Thick Skull'],                                                                               notes: null,                          includedWith: null },
  { name: "Brick Far'th",                            races: [],                                                                                                                                                     price: 290000, ma: 5, st: 5, ag: 2, av: 9,  skills: ['Loner', 'Bone-head', 'Mighty Blow', 'Nerves of Steel', 'Strong Arm', 'Thick Skull', 'Throw Team-Mate'],                                                    notes: null,                          includedWith: null },
  { name: 'Grotty',                                  races: [],                                                                                                                                                     price:    null, ma: 6, st: 2, ag: 4, av: 7,  skills: ['Loner', 'Dodge', 'Right Stuff', 'Stunty'],                                                                                                               notes: "Included with Brick Far'th",  includedWith: "Brick Far'th" },
  { name: "Bryce 'The Slice' Cambuel",               races: ['Khemri', 'Undead'],                                                                                                                                   price: 130000, ma: 5, st: 3, ag: 2, av: 8,  skills: ['Chainsaw', 'Loner', 'Regeneration', 'Secret Weapon', 'Stand Firm', 'Thick Skull'],                                                                          notes: null,                          includedWith: null },
  { name: 'Bulla Shardhorn',                         races: ['Nurgle'],                                                                                                                                             price: 230000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Block', 'Extra Arms', 'Foul Appearance', 'Horns', 'Loner', "Nurgle's Rot", 'Regeneration', 'Stab', 'Two Heads'],                                          notes: null,                          includedWith: null },
  { name: 'Cindy Piewhistle',                        races: ['Halfling'],                                                                                                                                           price:  50000, ma: 5, st: 2, ag: 3, av: 6,  skills: ['Dodge', 'Accurate', 'Bombardier', 'Loner', 'Secret Weapon', 'Stunty'],                                                                                   notes: null,                          includedWith: null },
  { name: 'Count Luthor Von Drakenborg',              races: ['Necromantic', 'Undead', 'Vampire'],                                                                                                                   price: 390000, ma: 6, st: 5, ag: 4, av: 9,  skills: ['Loner', 'Block', 'Hypnotic Gaze', 'Regeneration', 'Side Step'],                                                                                           notes: null,                          includedWith: null },
  { name: 'Crazy Igor',                              races: ['Chaos Pact', 'Vampire'],                                                                                                                              price: 120000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Dauntless', 'Regeneration', 'Thick Skull'],                                                                                                     notes: 'Can be bitten by a Vampire',  includedWith: null },
  { name: 'Curnoth Darkwold',                        races: ['Wood Elf'],                                                                                                                                           price: 240000, ma: 7, st: 3, ag: 4, av: 7,  skills: ['Loner', 'Frenzy', 'Wrestle', 'Dodge', 'Jump Up', 'Leap'],                                                                                                 notes: null,                          includedWith: null },
  { name: 'Deeproot Strongbranch',                   races: ['Halfling'],                                                                                                                                           price: 300000, ma: 2, st: 7, ag: 1, av: 10, skills: ['Loner', 'Block', 'Mighty Blow', 'Stand Firm', 'Strong Arm', 'Thick Skull', 'Throw Team-Mate'],                                                             notes: null,                          includedWith: null },
  { name: 'Dolfar Longstride',                       races: ['Elf', 'High Elf'],                                                                                                                                   price: 150000, ma: 7, st: 3, ag: 4, av: 7,  skills: ['Loner', 'Diving Catch', 'Hail Mary Pass', 'Kick', 'Kick-off Return', 'Pass Block'],                                                                       notes: null,                          includedWith: null },
  { name: 'Drull',                                   races: ['Lizardman'],                                                                                                                                          price: 190000, ma: 8, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Side Step', 'Dodge', 'Stab', 'Stunty'],                                                                                                        notes: null,                          includedWith: null },
  { name: 'Dribl',                                   races: [],                                                                                                                                                     price:    null, ma: 8, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Side Step', 'Dodge', 'Dirty Player', 'Sneaky Git', 'Stunty'],                                                                                notes: 'Included with Drull',         includedWith: 'Drull' },
  { name: 'Eldril Sidewinder',                       races: ['Dark Elf', 'Elf', 'High Elf', 'Wood Elf'],                                                                                                           price: 200000, ma: 8, st: 3, ag: 4, av: 7,  skills: ['Loner', 'Catch', 'Dodge', 'Hypnotic Gaze', 'Nerves of Steel', 'Pass Block'],                                                                              notes: null,                          includedWith: null },
  { name: 'Elijah Doom',                             races: ['Dark Elf', 'Elf'],                                                                                                                                   price: 190000, ma: 6, st: 3, ag: 4, av: 9,  skills: ['Fend', 'Guard', 'Loner', 'Stand Firm', 'Wrestle'],                                                                                                       notes: null,                          includedWith: null },
  { name: 'Fezglitch',                               races: ['Skaven', 'Underworld'],                                                                                                                              price: 100000, ma: 4, st: 7, ag: 3, av: 7,  skills: ['Loner', 'Ball & Chain', 'Disturbing Presence', 'Foul Appearance', 'No Hands', 'Secret Weapon'],                                                           notes: null,                          includedWith: null },
  { name: 'Flint Churnblade',                        races: ['Dwarf'],                                                                                                                                             price: 130000, ma: 5, st: 3, ag: 2, av: 8,  skills: ['Loner', 'Block', 'Chainsaw', 'Secret Weapon', 'Thick Skull'],                                                                                            notes: null,                          includedWith: null },
  { name: 'Frank N Stein',                           races: ['Human', 'Necromantic', 'Undead'],                                                                                                                    price: 270000, ma: 4, st: 5, ag: 1, av: 9,  skills: ['Break Tackle', 'Mighty Blow', 'Stand Firm', 'Thick Skull', 'Loner', 'Regeneration'],                                                                    notes: null,                          includedWith: null },
  { name: 'Fungus the Loon',                         races: ['Goblin'],                                                                                                                                            price:  80000, ma: 4, st: 7, ag: 3, av: 7,  skills: ['Loner', 'Ball & Chain', 'Mighty Blow', 'No Hands', 'Secret Weapon', 'Stunty'],                                                                          notes: null,                          includedWith: null },
  { name: "G'Ral Blodschüker",                       races: ['Necromantic', 'Undead', 'Vampire'],                                                                                                                  price: 160000, ma: 7, st: 3, ag: 3, av: 7,  skills: ['Catch', 'Dodge', 'Loner', 'Sure Feet', 'Wrestle'],                                                                                                       notes: null,                          includedWith: null },
  { name: 'Glart Smashrip',                          races: ['Skaven', 'Underworld'],                                                                                                                              price: 190000, ma: 5, st: 4, ag: 2, av: 8,  skills: ['Block', 'Grab', 'Juggernaut', 'Stand Firm', 'Claw', 'Loner'],                                                                                             notes: null,                          includedWith: null },
  { name: 'Glart Smashrip Jr.',                      races: ['Skaven', 'Underworld'],                                                                                                                              price: 210000, ma: 7, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Block', 'Claw', 'Juggernaut'],                                                                                                                  notes: null,                          includedWith: null },
  { name: 'Gloriel Summerbloom',                     races: ['Wood Elf'],                                                                                                                                          price: 160000, ma: 7, st: 2, ag: 4, av: 7,  skills: ['Loner', 'Sure Hands', 'Dodge', 'Side Step', 'Accurate', 'Pass'],                                                                                         notes: null,                          includedWith: null },
  { name: 'Glotl Stop',                              races: ['Amazon', 'Lizardman'],                                                                                                                               price: 360000, ma: 6, st: 6, ag: 1, av: 9,  skills: ['Loner', 'Frenzy', 'Mighty Blow', 'Thick Skull', 'Prehensile Tail', 'Wild Animal'],                                                                      notes: null,                          includedWith: null },
  { name: 'Gobbler Grimlich',                        races: ['Chaos', 'Chaos Pact', 'Underworld'],                                                                                                                 price: 230000, ma: 5, st: 4, ag: 2, av: 9,  skills: ['Leap', 'Big Hand', 'Disturbing Presence', 'Tentacles', 'Very Long Legs', 'Loner', 'Regeneration', 'Monstrous Mouth'],                                     notes: null,                          includedWith: null },
  { name: 'Grashnak Blackhoof',                      races: ['Chaos', 'Chaos Dwarf', 'Nurgle'],                                                                                                                    price: 310000, ma: 6, st: 6, ag: 2, av: 8,  skills: ['Loner', 'Frenzy', 'Horns', 'Mighty Blow', 'Thick Skull'],                                                                                                notes: null,                          includedWith: null },
  { name: "Gretchen Wächter 'The Blood Bowl Widow'", races: ['Necromantic', 'Undead', 'Vampire'],                                                                                                                  price: 280000, ma: 7, st: 3, ag: 4, av: 8,  skills: ['Disturbing Presence', 'Dodge', 'Foul Appearance', 'Jump Up', 'Loner', 'No Hands', 'Regeneration', 'Shadowing', 'Side Step'],                              notes: null,                          includedWith: null },
  { name: 'Griff Oberwald',                          races: ['Human'],                                                                                                                                             price: 320000, ma: 7, st: 4, ag: 4, av: 8,  skills: ['Loner', 'Block', 'Dodge', 'Fend', 'Sprint', 'Sure Feet'],                                                                                                notes: null,                          includedWith: null },
  { name: 'Grim Ironjaw',                            races: ['Dwarf'],                                                                                                                                             price: 220000, ma: 5, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Block', 'Dauntless', 'Frenzy', 'Multiple Block', 'Thick Skull'],                                                                                  notes: null,                          includedWith: null },
  { name: 'Guffle Pusmaw',                           races: ['Nurgle'],                                                                                                                                            price: 210000, ma: 5, st: 3, ag: 4, av: 9,  skills: ['Loner', 'Foul Appearance', "Nurgle's Rot", 'Monstrous Mouth'],                                                                                          notes: null,                          includedWith: null },
  { name: 'Hack Enslash',                            races: ['Necromantic'],                                                                                                                                       price: 120000, ma: 6, st: 3, ag: 2, av: 7,  skills: ['Loner', 'Chainsaw', 'Regeneration', 'Secret Weapon', 'Side Step'],                                                                                        notes: null,                          includedWith: null },
  { name: 'Hakflem Skuttlespike',                    races: ['Skaven'],                                                                                                                                            price: 200000, ma: 9, st: 3, ag: 4, av: 7,  skills: ['Loner', 'Dodge', 'Extra Arms', 'Prehensile Tail', 'Two Heads'],                                                                                          notes: null,                          includedWith: null },
  { name: 'Headsplitter',                            races: ['Skaven'],                                                                                                                                            price: 340000, ma: 6, st: 6, ag: 3, av: 8,  skills: ['Loner', 'Frenzy', 'Mighty Blow', 'Prehensile Tail'],                                                                                                     notes: null,                          includedWith: null },
  { name: 'Helmut Wulf',                             races: ['Amazon', 'Chaos Pact', 'Human', 'Lizardman', 'Norse', 'Slann', 'Vampire'],                                                                           price: 110000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Chainsaw', 'Secret Weapon', 'Stand Firm'],                                                                                                      notes: null,                          includedWith: null },
  { name: 'Hemlock',                                 races: ['Slann'],                                                                                                                                             price: 170000, ma: 8, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Block', 'Dodge', 'Side Step', 'Jump Up', 'Stab', 'Stunty'],                                                                                    notes: null,                          includedWith: null },
  { name: 'Horkon Heartripper',                      races: ['Dark Elf'],                                                                                                                                          price: 210000, ma: 7, st: 3, ag: 4, av: 7,  skills: ['Loner', 'Dodge', 'Leap', 'Multiple Block', 'Shadowing', 'Stab'],                                                                                        notes: null,                          includedWith: null },
  { name: 'Hthark the Unstoppable',                  races: ['Chaos Dwarf'],                                                                                                                                       price: 330000, ma: 6, st: 5, ag: 2, av: 9,  skills: ['Loner', 'Block', 'Break Tackle', 'Juggernaut', 'Sprint', 'Sure Feet', 'Thick Skull'],                                                                    notes: null,                          includedWith: null },
  { name: 'Hubris Rakarth',                          races: ['Dark Elf', 'Elf'],                                                                                                                                   price: 260000, ma: 7, st: 4, ag: 4, av: 8,  skills: ['Loner', 'Block', 'Dirty Player', 'Jump Up', 'Mighty Blow', 'Strip Ball'],                                                                                notes: null,                          includedWith: null },
  { name: 'Humerus Carpal',                          races: [],                                                                                                                                                    price: 130000, ma: 7, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Catch', 'Dodge', 'Regeneration', 'Nerves of Steel'],                                                                                            notes: null,                          includedWith: null },
  { name: 'Icepelt Hammerblow',                      races: ['Norse'],                                                                                                                                             price: 330000, ma: 5, st: 6, ag: 1, av: 8,  skills: ['Loner', 'Claw', 'Disturbing Presence', 'Frenzy', 'Regeneration', 'Thick Skull'],                                                                          notes: null,                          includedWith: null },
  { name: 'Ithaca Benoin',                           races: ['Dark Elf'],                                                                                                                                          price: 220000, ma: 7, st: 3, ag: 3, av: 7,  skills: ['Loner', 'Accurate', 'Dump Off', 'Nerves of Steel', 'Pass', 'Regeneration', 'Sure Hands'],                                                               notes: null,                          includedWith: null },
  { name: "Ivan 'The Animal' Deathshroud",           races: ['Khemri', 'Necromantic', 'Undead'],                                                                                                                   price: 230000, ma: 6, st: 4, ag: 2, av: 8,  skills: ['Block', 'Disturbing Presence', 'Juggernaut', 'Loner', 'Regeneration', 'Strip Ball', 'Tackle'],                                                           notes: null,                          includedWith: null },
  { name: 'J Earlice',                               races: ['Necromantic', 'Vampire'],                                                                                                                            price: 180000, ma: 8, st: 3, ag: 3, av: 7,  skills: ['Loner', 'Catch', 'Diving Catch', 'Dodge', 'Sprint'],                                                                                                     notes: null,                          includedWith: null },
  { name: 'Jordell Freshbreeze',                     races: ['Elf', 'Wood Elf'],                                                                                                                                   price: 260000, ma: 8, st: 3, ag: 5, av: 7,  skills: ['Loner', 'Block', 'Diving Catch', 'Dodge', 'Leap', 'Side Step'],                                                                                          notes: null,                          includedWith: null },
  { name: 'Karla von Kill',                          races: ['Amazon', 'Halfling', 'Human', 'Norse'],                                                                                                              price: 220000, ma: 6, st: 4, ag: 3, av: 8,  skills: ['Block', 'Dauntless', 'Dodge', 'Jump Up', 'Loner'],                                                                                                       notes: null,                          includedWith: null },
  { name: 'Kiroth Krakeneye',                        races: ['Dark Elf', 'Elf'],                                                                                                                                   price: 170000, ma: 7, st: 3, ag: 4, av: 8,  skills: ['Disturbing Presence', 'Foul Appearance', 'Loner', 'Pass Block', 'Tackle', 'Tentacles'],                                                                 notes: null,                          includedWith: null },
  { name: 'Kreek Rustgouger',                        races: ['Skaven', 'Underworld'],                                                                                                                              price: 130000, ma: 5, st: 7, ag: 2, av: 9,  skills: ['Mighty Blow', 'Prehensile Tail', 'Ball & Chain', 'Loner', 'No Hands', 'Secret Weapon'],                                                                   notes: null,                          includedWith: null },
  { name: 'Lewdgrip Whiparm',                        races: ['Chaos', 'Chaos Pact', 'Nurgle'],                                                                                                                     price: 160000, ma: 6, st: 3, ag: 3, av: 9,  skills: ['Dodge', 'Loner', 'Pass', 'Strong Arm', 'Sure Hands', 'Tentacles'],                                                                                        notes: null,                          includedWith: null },
  { name: 'Lord Borak the Despoiler',                races: ['Chaos', 'Nurgle'],                                                                                                                                   price: 300000, ma: 5, st: 5, ag: 3, av: 9,  skills: ['Loner', 'Block', 'Dirty Player', 'Mighty Blow'],                                                                                                         notes: null,                          includedWith: null },
  { name: 'Lottabottol',                             races: ['Slann'],                                                                                                                                             price: 220000, ma: 8, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Catch', 'Diving Tackle', 'Jump Up', 'Leap', 'Pass Block', 'Shadowing', 'Very Long Legs'],                                                      notes: null,                          includedWith: null },
  { name: 'Lucian Swift',                            races: ['Elf', 'High Elf', 'Wood Elf'],                                                                                                                       price: 390000, ma: 7, st: 3, ag: 4, av: 8,  skills: ['Loner', 'Block', 'Tackle', 'Mighty Blow'],                                                                                                               notes: null,                          includedWith: null },
  { name: 'Valen Swift',                             races: [],                                                                                                                                                    price:    null, ma: 7, st: 3, ag: 5, av: 7,  skills: ['Loner', 'Accurate', 'Sure Hands', 'Nerves of Steel', 'Pass', 'Safe Throw'],                                                                          notes: 'Included with Lucian Swift',  includedWith: 'Lucian Swift' },
  { name: 'Madcap Miggz',                            races: ['Goblin', 'Underworld'],                                                                                                                              price: 170000, ma: 6, st: 4, ag: 3, av: 8,  skills: ['Leap', 'Break Tackle', 'Claw', 'Very Long Legs', 'Loner', 'No Hands', 'Wild Animal'],                                                                     notes: null,                          includedWith: null },
  { name: 'Maple Highgrove',                         races: ['Wood Elf'],                                                                                                                                          price: 300000, ma: 3, st: 5, ag: 1, av: 10, skills: ['Loner', 'Grab', 'Mighty Blow', 'Stand Firm', 'Thick Skull', 'Tentacles'],                                                                                notes: null,                          includedWith: null },
  { name: 'Max Spleenripper',                        races: ['Chaos', 'Nurgle'],                                                                                                                                   price: 130000, ma: 5, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Chainsaw', 'Secret Weapon'],                                                                                                                   notes: null,                          includedWith: null },
  { name: 'Mighty Zug',                              races: ['Human'],                                                                                                                                             price: 260000, ma: 4, st: 5, ag: 2, av: 9,  skills: ['Loner', 'Block', 'Mighty Blow'],                                                                                                                         notes: null,                          includedWith: null },
  { name: 'Mordrix Hex',                             races: ['Dark Elf'],                                                                                                                                          price: 230000, ma: 7, st: 3, ag: 4, av: 7,  skills: ['Block', 'Dauntless', 'Dodge', 'Fend', 'Frenzy', 'Loner', 'Mighty Blow'],                                                                                notes: null,                          includedWith: null },
  { name: "Morg 'n' Thorg",                          races: ['Amazon', 'Chaos', 'Chaos Dwarf', 'Chaos Pact', 'Dark Elf', 'Dwarf', 'Elf', 'Goblin', 'Halfling', 'High Elf', 'Human', 'Lizardman', 'Norse', 'Nurgle', 'Ogre', 'Orc', 'Skaven', 'Slann', 'Underworld', 'Vampire', 'Wood Elf'],  price: 430000, ma: 6, st: 6, ag: 3, av: 10, skills: ['Loner', 'Block', 'Mighty Blow', 'Thick Skull', 'Throw Team-Mate'],   notes: null,      includedWith: null },
  { name: 'Neddley Verrüca',                         races: ['Halfling'],                                                                                                                                          price:  70000, ma: 5, st: 2, ag: 3, av: 6,  skills: ['Dodge', 'Loner', 'Secret Weapon', 'Stab', 'Stunty', 'Leap', 'Very Long Legs'],                                                                          notes: null,                          includedWith: null },
  { name: 'Nobbla Blackwart',                        races: ['Chaos Dwarf', 'Goblin', 'Ogre', 'Underworld'],                                                                                                       price: 130000, ma: 6, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Block', 'Dodge', 'Chainsaw', 'Secret Weapon', 'Stunty'],                                                                                        notes: null,                          includedWith: null },
  { name: 'Prince Moranion',                         races: ['Elf', 'High Elf'],                                                                                                                                   price: 230000, ma: 7, st: 4, ag: 4, av: 8,  skills: ['Loner', 'Block', 'Dauntless', 'Tackle', 'Wrestle'],                                                                                                      notes: null,                          includedWith: null },
  { name: 'Puggy Baconbreath',                       races: ['Halfling', 'Human'],                                                                                                                                 price: 140000, ma: 5, st: 3, ag: 3, av: 6,  skills: ['Loner', 'Block', 'Dodge', 'Nerves of Steel', 'Right Stuff', 'Stunty'],                                                                                  notes: null,                          includedWith: null },
  { name: 'Quetzal Leap',                            races: ['Slann'],                                                                                                                                             price: 250000, ma: 8, st: 2, ag: 4, av: 7,  skills: ['Loner', 'Catch', 'Diving Catch', 'Fend', 'Kick-off Return', 'Leap', 'Nerves of Steel', 'Very Long Legs'],                                                notes: null,                          includedWith: null },
  { name: 'Ramtut III',                              races: ['Khemri', 'Necromantic', 'Undead'],                                                                                                                   price: 360000, ma: 5, st: 6, ag: 1, av: 9,  skills: ['Loner', 'Break Tackle', 'Mighty Blow', 'Regeneration', 'Wrestle'],                                                                                      notes: null,                          includedWith: null },
  { name: 'Rashnak Backstabber',                     races: ['Chaos Dwarf'],                                                                                                                                       price: 200000, ma: 7, st: 3, ag: 3, av: 7,  skills: ['Loner', 'Dodge', 'Side Step', 'Sneaky Git', 'Stab'],                                                                                                     notes: null,                          includedWith: null },
  { name: 'Rasta Tailspike',                         races: ['Skaven'],                                                                                                                                            price: 120000, ma: 8, st: 3, ag: 3, av: 7,  skills: ['Loner', 'Catch', 'Extra Arms'],                                                                                                                          notes: null,                          includedWith: null },
  { name: 'Ripper',                                  races: ['Goblin', 'Orc'],                                                                                                                                     price: 270000, ma: 4, st: 6, ag: 1, av: 9,  skills: ['Loner', 'Grab', 'Mighty Blow', 'Regeneration', 'Throw Team-Mate'],                                                                                       notes: null,                          includedWith: null },
  { name: "Rotten' Rick Bupkeis",                    races: ['Undead'],                                                                                                                                            price: 110000, ma: 4, st: 3, ag: 2, av: 8,  skills: ['Loner', 'Dirty Player', 'Sneaky Git', 'Regeneration'],                                                                                                 notes: null,                          includedWith: null },
  { name: 'Roxanna Darknail',                        races: ['Amazon', 'Dark Elf'],                                                                                                                                price: 250000, ma: 8, st: 3, ag: 5, av: 7,  skills: ['Loner', 'Dodge', 'Frenzy', 'Jump Up', 'Juggernaut', 'Leap'],                                                                                          notes: null,                          includedWith: null },
  { name: 'Rumblelow Sheepskin',                     races: ['Halfling'],                                                                                                                                           price: 170000, ma: 6, st: 3, ag: 3, av: 7,  skills: ['Block', 'Horns', 'Juggernaut', 'Loner', 'No Hands', 'Tackle', 'Thick Skull'],                                                                          notes: null,                          includedWith: null },
  { name: 'Scrappa Sorehead',                        races: ['Goblin', 'Ogre', 'Orc'],                                                                                                                             price: 150000, ma: 7, st: 2, ag: 3, av: 7,  skills: ['Loner', 'Dirty Player', 'Dodge', 'Leap', 'Right Stuff', 'Sprint', 'Stunty', 'Sure Feet', 'Very Long Legs'],                                               notes: null,                          includedWith: null },
  { name: 'Scyla Anfingrimm',                        races: ['Chaos', 'Norse'],                                                                                                                                    price: 250000, ma: 5, st: 5, ag: 1, av: 9,  skills: ['Frenzy', 'Thick Skull', 'Claw', 'Prehensile Tail', 'Loner', 'Wild Animal'],                                                                              notes: null,                          includedWith: null },
  { name: 'Setekh',                                  races: ['Necromantic'],                                                                                                                                       price: 220000, ma: 6, st: 4, ag: 2, av: 8,  skills: ['Loner', 'Block', 'Break Tackle', 'Juggernaut', 'Regeneration', 'Strip Ball'],                                                                          notes: null,                          includedWith: null },
  { name: 'Sinnedbad',                               races: [],                                                                                                                                                    price:  80000, ma: 6, st: 3, ag: 2, av: 7,  skills: ['Loner', 'Block', 'Jump Up', 'Pass Block', 'Regeneration', 'Secret Weapon', 'Side Step', 'Stab'],                                                      notes: null,                          includedWith: null },
  { name: 'Skitter Stab-Stab',                       races: ['Skaven', 'Underworld'],                                                                                                                              price: 160000, ma: 9, st: 2, ag: 4, av: 7,  skills: ['Loner', 'Dodge', 'Prehensile Tail', 'Shadowing', 'Stab'],                                                                                                notes: null,                          includedWith: null },
  { name: 'Skrull Halfheight',                       races: ['Khemri', 'Undead'],                                                                                                                                  price: 190000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Sure Hands', 'Thick Skull', 'Accurate', 'Nerves of Steel', 'Pass', 'Regeneration'],                                                           notes: null,                          includedWith: null },
  { name: 'Slibli',                                  races: ['Slann'],                                                                                                                                             price: 250000, ma: 7, st: 4, ag: 1, av: 9,  skills: ['Loner', 'Block', 'Grab', 'Guard', 'Stand Firm'],                                                                                                        notes: null,                          includedWith: null },
  { name: 'Soaren Hightower',                        races: ['High Elf'],                                                                                                                                          price: 180000, ma: 6, st: 3, ag: 4, av: 8,  skills: ['Loner', 'Fend', 'Kick-off Return', 'Pass', 'Safe Throw', 'Sure Hands', 'Strong Arm'],                                                                  notes: null,                          includedWith: null },
  { name: 'Swiftvine Glimmershard',                  races: ['Wood Elf'],                                                                                                                                          price: 130000, ma: 7, st: 2, ag: 3, av: 6,  skills: ['Loner', 'Fend', 'Side Step', 'Disturbing Presence', 'Stab', 'Stunty'],                                                                                  notes: null,                          includedWith: null },
  { name: "Throttlesnot 'The Impaler'",              races: ['Necromantic', 'Undead'],                                                                                                                             price: 100000, ma: 6, st: 2, ag: 3, av: 7,  skills: ['Dirty Player', 'Dodge', 'Leap', 'Loner', 'Regeneration', 'Secret Weapon', 'Stab', 'Stunty'],                                                           notes: null,                          includedWith: null },
  { name: 'Tolly Glocklinger',                       races: ['Nurgle'],                                                                                                                                            price: 110000, ma: 3, st: 7, ag: 2, av: 9,  skills: ['Ball & Chain', 'Disturbing Presence', 'Foul Appearance', 'Loner', 'No Hands', "Nurgle's Rot", 'Secret Weapon', 'Stand Firm'],                           notes: null,                          includedWith: null },
  { name: 'Ugroth Bolgrot',                          races: ['Orc', 'Chaos Pact'],                                                                                                                                price: 100000, ma: 5, st: 3, ag: 3, av: 9,  skills: ['Loner', 'Chainsaw', 'Secret Weapon'],                                                                                                                   notes: null,                          includedWith: null },
  { name: 'Varag Ghoul-Chewer',                      races: ['Orc'],                                                                                                                                               price: 290000, ma: 6, st: 4, ag: 3, av: 9,  skills: ['Loner', 'Block', 'Jump Up', 'Mighty Blow', 'Thick Skull'],                                                                                             notes: null,                          includedWith: null },
  { name: "Wilhelm 'The Wolf-Man' Chaney",           races: ['Necromantic', 'Norse', 'Vampire'],                                                                                                                   price: 240000, ma: 8, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Catch', 'Claw', 'Frenzy', 'Regeneration', 'Wrestle'],                                                                                         notes: null,                          includedWith: null },
  { name: 'Willow Rosebark',                         races: ['Amazon', 'Halfling', 'Wood Elf'],                                                                                                                    price: 150000, ma: 5, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Dauntless', 'Side Step', 'Thick Skull'],                                                                                                       notes: null,                          includedWith: null },
  { name: 'Withergrasp Doubledrool',                 races: ['Chaos', 'Nurgle', 'Chaos Pact'],                                                                                                                     price: 170000, ma: 6, st: 3, ag: 3, av: 8,  skills: ['Loner', 'Prehensile Tail', 'Tackle', 'Tentacles', 'Two Heads', 'Wrestle'],                                                                               notes: null,                          includedWith: null },
  { name: 'Zara the Slayer',                         races: ['Amazon', 'Dwarf', 'High Elf', 'Human', 'Norse'],                                                                                                     price: 270000, ma: 6, st: 4, ag: 3, av: 8,  skills: ['Loner', 'Block', 'Dauntless', 'Dodge', 'Jump Up', 'Stab', 'Stakes'],                                                                                    notes: null,                          includedWith: null },
  { name: 'Zolcath the Zoat',                        races: ['Amazon', 'Lizardman', 'Wood Elf'],                                                                                                                   price: 280000, ma: 5, st: 5, ag: 2, av: 9,  skills: ['Loner', 'Sure Feet', 'Juggernaut', 'Mighty Blow', 'Disturbing Presence', 'Prehensile Tail', 'Regeneration'],                                            notes: null,                          includedWith: null },
  { name: 'Zzharg Madeye',                           races: ['Chaos Dwarf', 'Chaos Pact'],                                                                                                                         price:  90000, ma: 4, st: 4, ag: 3, av: 9,  skills: ['Loner', 'Hail Mary Pass', 'Pass', 'Secret Weapon', 'Strong Arm', 'Sure Hands', 'Tackle', 'Thick Skull'],                                                 notes: null,                          includedWith: null },
]

// Name mismatches between CSV data and what was actually seeded in the DB
const SKILL_ALIASES: Record<string, string> = {
  'Bone-head':       'Bone Head',
  'Nerves of Steel': 'Nerves of Iron',
  'Claw':            'Claws',
  'Dump Off':        'Dump-Off',
}

const RACE_ALIASES: Record<string, string> = {
  'Lizardman': 'Lizardmen',
  'Elf':       'Elf / Pro Elf',
}

function resolveSkill(name: string): string { return SKILL_ALIASES[name] ?? name }
function resolveRace(name: string):  string { return RACE_ALIASES[name]  ?? name }

async function main() {
  console.log(`Seeding ${STARS.length} MdStarPlayer records...`)

  const allSkills = await prisma.skill.findMany({ select: { id: true, name: true } })
  const skillById = new Map(allSkills.map((s) => [s.name.toLowerCase(), s.id]))

  const allRaces = await prisma.race.findMany({ select: { id: true, name: true } })
  const raceById = new Map(allRaces.map((r) => [r.name.toLowerCase(), r.id]))

  const nameToId = new Map<string, string>()

  // Pass 1: upsert each star player without includedWith
  for (const sp of STARS) {
    const skillIds = sp.skills
      .map((n) => skillById.get(resolveSkill(n).toLowerCase()))
      .filter((id): id is string => id !== undefined)
    const raceIds = sp.races
      .map((n) => raceById.get(resolveRace(n).toLowerCase()))
      .filter((id): id is string => id !== undefined)

    const unmatched = sp.skills.filter((n) => !skillById.has(resolveSkill(n).toLowerCase()))
    if (unmatched.length) console.log(`  ⚠ ${sp.name} — unmatched skills: ${unmatched.join(', ')}`)

    const unmatchedR = sp.races.filter((n) => !raceById.has(resolveRace(n).toLowerCase()))
    if (unmatchedR.length) console.log(`  ⚠ ${sp.name} — unmatched races: ${unmatchedR.join(', ')}`)

    const record = await prisma.mdStarPlayer.upsert({
      where:  { name: sp.name },
      update: {
        price: sp.price, ma: sp.ma, st: sp.st, ag: sp.ag, av: sp.av,
        notes: sp.notes,
        skills: { set: skillIds.map((id) => ({ id })) },
        races:  { set: raceIds.map((id) => ({ id })) },
      },
      create: {
        name: sp.name, price: sp.price,
        ma: sp.ma, st: sp.st, ag: sp.ag, av: sp.av,
        notes: sp.notes,
        skills: { connect: skillIds.map((id) => ({ id })) },
        races:  { connect: raceIds.map((id) => ({ id })) },
      },
    })
    nameToId.set(sp.name, record.id)
  }

  // Pass 2: wire up companion self-references
  for (const sp of STARS) {
    if (!sp.includedWith) continue
    const companionId = nameToId.get(sp.name)
    const parentId    = nameToId.get(sp.includedWith)
    if (!companionId || !parentId) {
      console.log(`  ⚠ Could not resolve includedWith for ${sp.name} → ${sp.includedWith}`)
      continue
    }
    await prisma.mdStarPlayer.update({
      where: { id: companionId },
      data:  { includedWithId: parentId },
    })
  }

  console.log('Done.')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
